print( "patternA      patternB       patternC       patternD ")
print( "*             ******                *        ******  ")
print( "**             *****              **          *****  ")
print( " ***            ****             ***           ****  ")
print( " ****            ***            ****            ***  ")
print( " *****            **           *****             **  ")
print( " ******            *          ******              *  ")